<Project Sdk="Godot.NET.Sdk/4.6.1">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net10.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <RootNamespace>SingleplayerAutobattler</RootNamespace>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="GeWuYou.GFramework" Version="0.0.193"/>
        <PackageReference Include="GeWuYou.GFramework.Godot" Version="0.0.193"/>
        <PackageReference Include="GeWuYou.GFramework.Godot.SourceGenerators" Version="0.0.193"/>
        <PackageReference Include="GeWuYou.GFramework.SourceGenerators" Version="0.0.193"/>
        <PackageReference Update="Meziantou.Analyzer" Version="3.0.15">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Update="Meziantou.Polyfill" Version="1.0.101">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Riok.Mapperly" Version="4.3.1"/>
        <PackageReference Include="Mediator.SourceGenerator" Version="3.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <Compile Remove="scenes\**"/>
        <Compile Remove="script_templates\**" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Remove="scenes\**" />
        <EmbeddedResource Remove="script_templates\**" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="scripts\enums\game\" />
        <Folder Include="scripts\events\" />
        <Folder Include="scripts\xp_button\" />
    </ItemGroup>
    <ItemGroup>
        <Content Include=".github\dependabot.yml" />
        <Content Include=".github\workflows\auto-tag.yml" />
        <Content Include=".github\workflows\ci.yml" />
        <Content Include=".github\workflows\codeql.yml" />
        <Content Include=".github\workflows\release.yml" />
        <Content Include="global\AudioManager.cs.uid" />
        <Content Include="global\audio_manager.tscn" />
        <Content Include="global\GameEntryPoint.cs.uid" />
        <Content Include="global\game_entry_point.tscn" />
        <Content Include="global\GlobalInputController.cs.uid" />
        <Content Include="global\global_input_controller.tscn" />
        <Content Include="global\README.md" />
        <Content Include="global\SceneRoot.cs.uid" />
        <Content Include="global\SceneTransitionManager.cs.uid" />
        <Content Include="global\scene_root.tscn" />
        <Content Include="global\scene_transition_manager.tscn" />
        <Content Include="global\UiRoot.cs.uid" />
        <Content Include="global\ui_root.tscn" />
        <Content Include="scripts\core\GameArchitecture.cs.uid" />
        <Content Include="scripts\credits\Credits.cs.uid" />
        <Content Include="scripts\data\interfaces\ISaveStorageUtility.cs.uid" />
        <Content Include="scripts\data\model\GameSaveData.cs.uid" />
        <Content Include="scripts\data\model\LocalDataLocation.cs.uid" />
        <Content Include="scripts\data\model\README.md" />
        <Content Include="scripts\data\README.md" />
        <Content Include="scripts\enums\audio\BgmType.cs.uid" />
        <Content Include="scripts\enums\audio\SfxType.cs.uid" />
        <Content Include="scripts\enums\resources\TextureKey.cs.uid" />
        <Content Include="scripts\enums\scene\SceneKey.cs.uid" />
        <Content Include="scripts\enums\settings\SettingsChangedReason.cs.uid" />
        <Content Include="scripts\enums\ui\UiKey.cs.uid" />
        <Content Include="scripts\intro\Intro.cs.uid" />
        <Content Include="scripts\main_menu\MainMenu.cs.uid" />
        <Content Include="scripts\options_menu\OptionsMenu.cs.uid" />
        <Content Include="scripts\pause_menu\PauseMenu.cs.uid" />
        <Content Include="scripts\setting\SettingDataLocationProvider.cs.uid" />
        <Content Include="scripts\setting\SettingsDataRepository.cs.uid" />
        <Content Include="scripts\tests\Home.cs.uid" />
        <Content Include="scripts\tests\HomeUi.cs.uid" />
        <Content Include="scripts\tests\Scene1.cs.uid" />
        <Content Include="scripts\tests\Scene2.cs.uid" />
        <Content Include="scripts\utility\GodotTextureRegistry.cs.uid" />
        <Content Include="scripts\utility\IGodotTextureRegistry.cs.uid" />
    </ItemGroup>
</Project>